name: Run Tests
on: [push, pull_request]
jobs:
  test-cov:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      #----------------------------------------------
      #---- Checkout and install poetry and python
      #----------------------------------------------

      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      #----------------------------------------------
      #---- install dependencies
      #----------------------------------------------

      - name: poetry install
        run: poetry install

      #----------------------------------------------
      #---- Tests
      #----------------------------------------------

      - name: Run tests with code coverage report
        run: poetry run pytest --cov=pathdict test_all.py --cov-report term-missing
